import '../firebase-client.js';

const params = new URLSearchParams(location.search);
const restaurantId = params.get('restaurant') || 'ciasift';
const API_BASE = 'https://cia-smart-menu-demo.vercel.app';
const ORDERS_KEY = `cia-smart-menu-orders:${restaurantId}`;
const ORDER_NUMBER_KEY = `cia-smart-menu-next-order:${restaurantId}`;
const state = { menu: { categories: [], products: [] }, category: 'all', query: '', cart: new Map(), orders: loadOrders() };
const $ = (s) => document.querySelector(s);
const text = (v) => typeof v === 'string' ? v : v?.ru || v?.en || v?.hy || Object.values(v || {})[0] || '';
const id = (v) => typeof v === 'object' ? String(v?.id ?? v?.categoryId ?? '') : String(v ?? '');
function priceValue(p) { const raw = Number(p?.price); if (!Number.isFinite(raw)) return 0; return raw >= 100000 ? raw / 100 : raw; }
function price(p) { return `${Math.round(priceValue(p)).toLocaleString('ru-RU')} ֏`; }
function categoryOf(p) { return id(p?.categoryId ?? p?.category ?? p?.menuCategoryId); }
function visible() { return state.menu.products.filter(p => (state.category === 'all' || categoryOf(p) === state.category) && (!state.query || text(p.name).toLowerCase().includes(state.query))); }
function loadOrders() { try { const value = JSON.parse(localStorage.getItem(ORDERS_KEY) || '[]'); return Array.isArray(value) ? value : []; } catch { return []; } }
function saveOrders() { localStorage.setItem(ORDERS_KEY, JSON.stringify(state.orders.slice(0, 20))); }
function nextOrderNumber() { const current = Number(localStorage.getItem(ORDER_NUMBER_KEY) || '202'); const next = Number.isFinite(current) ? current + 1 : 203; localStorage.setItem(ORDER_NUMBER_KEY, String(next)); return next; }
function addOrderToHistory(items, total) { const order = { number: nextOrderNumber(), createdAt: new Date().toISOString(), status: 'Заказ отправлен', items: items.map(({ product, count }) => ({ productId: Number(product.id), name: text(product.name), price: priceValue(product), count })), total }; state.orders.unshift(order); saveOrders(); }
function addToCart(product) { const key = String(product.id); const item = state.cart.get(key); state.cart.set(key, { product, count: (item?.count || 0) + 1 }); renderCart(); }
function changeCart(idValue, delta) { const item = state.cart.get(String(idValue)); if (!item) return; item.count += delta; if (item.count <= 0) state.cart.delete(String(idValue)); renderCart(); }
function cartItems() { return [...state.cart.values()]; }
function cartTotal() { return cartItems().reduce((sum, x) => sum + priceValue(x.product) * x.count, 0); }
function cartCount() { return cartItems().reduce((sum, x) => sum + x.count, 0); }
function renderCategories() { const el = $('#categories'); el.innerHTML = [{ id: 'all', name: 'Все' }, ...state.menu.categories].map(c => `<button class="category ${String(c.id) === state.category ? 'active' : ''}" data-id="${c.id}">${text(c.name)}</button>`).join(''); el.querySelectorAll('button').forEach(b => b.onclick = () => { state.category = b.dataset.id; render(); }); }
function render() { const list = visible(); $('#count').textContent = `${list.length} блюд`; $('#products').innerHTML = list.map(p => { const image = p.photo || p.image || p.imageUrl || p.photo_url || ''; return `<article class="card" data-id="${p.id}"><div class="photo">${image ? `<img src="${image}" alt="${text(p.name)}" loading="lazy">` : 'Нет фото'}</div><div class="info"><h2>${text(p.name) || 'Без названия'}</h2><div class="price">${price(p)}</div></div></article>`; }).join('') || '<p>Блюда не найдены.</p>'; elBindCards(); renderCategories(); renderCart(); }
function elBindCards() { document.querySelectorAll('.card').forEach(card => card.onclick = () => { const product = state.menu.products.find(p => String(p.id) === card.dataset.id); if (product) addToCart(product); }); }
function renderCart() { const count = cartCount(); $('#cartButton').hidden = count === 0; $('#cartCount').textContent = count; $('#cartTotal').textContent = `${Math.round(cartTotal()).toLocaleString('ru-RU')} ֏`; const list = $('#cartItems'); list.innerHTML = cartItems().map(({ product, count }) => `<div class="cart-item"><div><strong>${text(product.name)}</strong><div>${price(product)} × ${count}</div></div><div class="qty"><button data-cart-id="${product.id}" data-delta="-1">−</button><span>${count}</span><button data-cart-id="${product.id}" data-delta="1">+</button></div></div>`).join('') || '<p>Корзина пуста</p>'; list.querySelectorAll('[data-cart-id]').forEach(b => b.onclick = () => changeCart(b.dataset.cartId, Number(b.dataset.delta))); }
function renderOrders() { const modal = $('#ordersModal'); if (!modal) return; const list = $('#ordersList'); list.innerHTML = state.orders.length ? state.orders.map(order => `<article class="order-history"><div class="order-history-head"><strong>Заказ №${order.number}</strong><span>${new Date(order.createdAt).toLocaleDateString('ru-RU')} · ${new Date(order.createdAt).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</span></div><div class="order-history-items">${order.items.map(item => `<div><span>${item.name}</span><span>× ${item.count}</span></div>`).join('')}</div><div class="order-history-foot"><strong>${Math.round(order.total).toLocaleString('ru-RU')} ֏</strong><span>✓ Заказ отправлен</span></div></article>`).join('') : '<div class="orders-empty"><div class="orders-empty-icon">🧾</div><strong>Заказов пока нет</strong><p>Здесь появятся ваши отправленные заказы.</p></div>'; }
function openOrders() { renderOrders(); $('#ordersModal').hidden = false; }
function closeOrders() { $('#ordersModal').hidden = true; }
function openCart() { $('#cartModal').hidden = false; renderCart(); }
function closeCart() { $('#cartModal').hidden = true; }
async function submitOrder() { const phone = $('#orderPhone').value.trim(); const name = $('#orderName').value.trim() || 'CIA Smart Menu'; const comment = $('#orderComment').value.trim(); const items = cartItems(); if (!items.length) return; const button = $('#submitOrder'); button.disabled = true; button.textContent = 'Отправка…'; $('#orderError').hidden = true; try { const response = await fetch(`${API_BASE}/api/create-order`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ confirm: true, spot_id: 1, phone, first_name: name, comment, products: items.map(({ product, count }) => ({ product_id: Number(product.id), count })) }) }); const data = await response.json(); if (!response.ok || !data.ok) throw new Error(data.error || 'Не удалось отправить заказ'); addOrderToHistory(items, cartTotal()); state.cart.clear(); closeCart(); const success = $('#success'); success.hidden = false; success.textContent = 'Заказ отправлен в Poster.'; renderCart(); window.setTimeout(() => { success.hidden = true; success.textContent = ''; }, 3000); } catch (e) { $('#orderError').hidden = false; $('#orderError').textContent = e.message; } finally { button.disabled = false; button.textContent = 'Отправить заказ'; } }
async function waitForFirebase() { if (window.ciaFirebase?.ready) return; await new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error('Firebase initialization timeout')), 10000); window.addEventListener('cia:firebase-ready', () => { clearTimeout(timer); resolve(); }, { once: true }); }); }
async function load() { try { await waitForFirebase(); state.menu = await window.ciaFirebase.loadPublicMenu(restaurantId); $('#restaurantName').textContent = text(state.menu.restaurant?.name) || restaurantId; render(); } catch (e) { console.error(e); $('#error').hidden = false; $('#error').textContent = `Не удалось загрузить меню: ${e.message}`; $('#restaurantName').textContent = restaurantId; } }
$('#search').oninput = e => { state.query = e.target.value.trim().toLowerCase(); render(); };
$('#cartButton').onclick = openCart; $('#closeCart').onclick = closeCart; $('#submitOrder').onclick = submitOrder; $('#ordersButton').onclick = openOrders; $('#closeOrders').onclick = closeOrders;
load();